#+title: My-Dijkstra

* Disclaimer
~This project was made to understand more about path-finding algorithms so its a basic implementation of the original dijkstra.~
This project started as a simple C program to solve pathfinding algorithms but now is a javascript implementation of a recursive pathfinding algorithm made by me. This implementation is not dijkstra as it is slow compared to dijkstra. Even though it is slower it is still a interesting algorithm.


* How to use this
The website auto generates two starting positions. then there are two buttons one for changing the grid size and one for doing the pathfinding.
** Generating new maps
- The default is 5 as it is almost instant.
- 6 takes one or two seconds.
- 7 takes too long and might freeze halfway
- These maps should be between 3 and 6. =WARNING DO NOT GO MORE THAN 6 IT WILL TAKE TOO LONG=

** Pathfinding
Once the pathfinding is finished the path will be colored.


* Future plans
- [ ] Make a website where it can be used with just a click
- [ ] Add more algorithms:
  - [ ] Actual Dijkstra
  - [ ] A* search
  - [ ] Breadth-first search
